database:
  redis_url: redis://127.0.0.1:6379/0
  url: postgresql+asyncpg://postgres:password@127.0.0.1:5433/simmiadb
llm:
  api_key: gAAAAABpqqSXBD260464eVkMDaR-yfBbnTZG1_1Z5YAAL9dDscgkxal1C6n7ZC-76OOf4MCAqSJsRfyIO-Ba0SmIY82BDWo42LEsMT7eWP87eUJV-RUdxsOTMBC6nUucbB_WkQlQV8QC
  provider: gemini
personality:
  description: A professional autonomous agent.
  name: Simmi
  owner: Sunny
  role: Personal AI Assistant & Executor
  tone: professional
storage_path: ./storage
telegram:
  allowed_user_ids:
  - 8167934166
  bot_token: gAAAAABpqqSXCkfbE9roTY6toshkNUA6bBaCAuzkSMQNfZv5TQTn6gf11OoI0c0iu0NUgbd7mVree-zw0py-iJpClYaMWipmcbvRynWL1VTFSi-iu-Re0UYQqHF7PGPfGGwvatmc8R5G
voice:
  elevenlabs_api_key: null
  elevenlabs_voice_id: ''
  enabled: true
  response_mode: text
whatsapp:
  enabled: false
  mode: none
